[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@superfluid-finance/ethereum-contracts=lib/superfluid-protocol-monorepo/packages/ethereum-contracts',
    '@openzeppelin/=lib/openzeppelin-contracts/',
]

gas_reports = ["Web3Referrals"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config